---
sidebar: sidebar 
permalink: faq_cloud_compliance.html 
keywords: faq, frequently asked questions, questions 
summary: Esta FAQ pode ajudar se você está apenas procurando uma resposta rápida para uma pergunta. 
---
= Perguntas frequentes sobre o Cloud Compliance
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Esta FAQ pode ajudar se você está apenas procurando uma resposta rápida para uma pergunta.



== O que é o Cloud Compliance?

O Cloud Compliance é uma nova oferta de nuvem da NetApp. Usando tecnologia orientada por inteligência artificial (AI), o Cloud Compliance ajuda as organizações a entender o contexto dos dados e identificar dados confidenciais em seus sistemas Cloud Volumes ONTAP hospedados na AWS ou Azure.

O Cloud Compliance fornece parâmetros pré-definidos (como categorias e tipos de informações confidenciais) para lidar com as novas regulamentações de conformidade de dados para privacidade e sensibilidade de dados, como GDPR, CCPA e muito mais.



== Por que devo usar o Cloud Compliance?

O Cloud Compliance ajuda você a:

* Cumprir as regulamentações de privacidade e conformidade de dados.
* Obedecer às políticas de retenção de dados.
* Localize e reporte facilmente dados específicos em resposta aos titulares dos dados, conforme exigido pelo GDPR, CCPA e outras regulamentações de privacidade de dados.




== Quais são os casos de uso comuns para o Cloud Compliance?

* Identificar informações pessoais identificáveis (PII).
* Identifique um amplo escopo de informações confidenciais conforme exigido pelas regulamentações de privacidade do GDPR e CCPA.
* Cumprir as novas e futuras regulamentações de privacidade de dados.


https://cloud.netapp.com/cloud-compliance["Saiba mais sobre os casos de uso do Cloud Compliance"^].



== Que tipos de dados podem ser verificados com o Cloud Compliance?

O Cloud Compliance é compatível com a verificação de dados não estruturados em protocolos NFS e CIFS. Atualmente, o Cloud Compliance verifica os dados gerenciados pelo Cloud Volumes ONTAP.

link:concept_cloud_compliance.html#how-scans-work["Saiba como as digitalizações funcionam"].



== Quais fornecedores de nuvem são compatíveis?

O Cloud Compliance opera como parte do Cloud Manager e, atualmente, é compatível com AWS e Azure. Isso proporciona à sua organização uma visibilidade unificada da privacidade entre diferentes fornecedores de nuvem. O suporte ao Google Cloud Platform (GCP) será adicionado em breve.



== Como faço para acessar o Cloud Compliance?

O Cloud Compliance é operado e gerenciado por meio do Cloud Manager. Você pode acessar os recursos de conformidade na nuvem a partir da guia *Compliance* no Cloud Manager.



== Como funciona o Cloud Compliance?

O Cloud Compliance implanta outra camada de inteligência artificial junto com seu sistema Cloud Manager e instâncias do Cloud Volumes ONTAP. Em seguida, ele verifica os dados no Cloud Volumes ONTAP e indexa os insights de dados encontrados.

link:concept_cloud_compliance.html["Saiba mais sobre como o Cloud Compliance funciona"].



== Quanto custa o Cloud Compliance?

O Cloud Compliance é oferecido como parte do Cloud Volumes ONTAP e não exige custos adicionais. Custos adicionais podem ser necessários no futuro para recursos personalizados.


NOTE: O Cloud Compliance requer a implantação de uma instância no seu provedor de nuvem, para a qual você será cobrado pelo seu provedor de nuvem.



== Com que frequência o Cloud Compliance verifica meus dados?

Os dados são alterados com frequência. Assim, o Cloud Compliance verifica seus dados continuamente sem impacto nos dados. Embora a digitalização inicial dos seus dados possa demorar mais tempo, as digitalizações subsequentes apenas analisam as alterações incrementais, o que reduz os tempos de digitalização do sistema.

link:concept_cloud_compliance.html#how-scans-work["Saiba como as digitalizações funcionam"].



== O Cloud Compliance oferece relatórios?

Sim. As informações oferecidas pelo Cloud Compliance podem ser relevantes para outras partes interessadas em suas organizações, por isso, permitimos que você gere relatórios para compartilhar os insights.

Os seguintes relatórios estão disponíveis para conformidade com a nuvem:

Relatório de avaliação de risco de privacidade:: Fornece insights de privacidade de seus dados e uma pontuação de risco de privacidade. link:task_generating_compliance_reports.html["Saiba mais"].
Relatório de solicitação de acesso do titular dos dados:: Permite que você extraia um relatório de todos os arquivos que contêm informações sobre o nome específico ou identificador pessoal de um titular de dados. link:task_responding_to_dsar.html["Saiba mais"].
Relatórios sobre um tipo de informação específico:: Estão disponíveis relatórios que incluem detalhes sobre os arquivos identificados que contêm dados pessoais e dados pessoais confidenciais. Você também pode ver os arquivos divididos por categoria e tipo de arquivo. link:task_controlling_private_data.html["Saiba mais"].




== Que tipo de instância ou VM é necessário para o Cloud Compliance?

* No Azure, o Cloud Compliance é executado em uma VM Standard_D16s_v3 com um disco de 512 GB.
* Na AWS, o Cloud Compliance é executado em uma instância do m5,4xlarge com um disco io1 de 500 GB.
+
Em regiões onde o m5,4xlarge não está disponível, o Cloud Compliance é executado em uma instância do m4,4xlarge.



link:concept_cloud_compliance.html["Saiba mais sobre como o Cloud Compliance funciona"].



== O desempenho da digitalização varia?

O desempenho da digitalização pode variar com base na largura de banda da rede e no tamanho médio do ficheiro no seu ambiente de nuvem.



== Como habilito o Cloud Compliance?

Você pode ativar o Cloud Compliance ao criar um novo ambiente de trabalho. Você pode ativá-lo em ambientes de trabalho existentes na guia *Compliance* (somente na primeira ativação) ou selecionando um ambiente de trabalho específico.

link:task_getting_started_compliance.html["Saiba como começar"].


NOTE: A ativação do Cloud Compliance resulta em uma verificação inicial imediata. Os resultados de conformidade são exibidos pouco depois.



== Como posso desativar o Cloud Compliance?

Você pode desativar o Cloud Compliance na página ambientes de trabalho depois de selecionar um ambiente de trabalho individual.

link:task_managing_compliance.html["Saiba mais"].


NOTE: Para remover completamente a instância do Cloud Compliance, você pode remover manualmente a instância do Cloud Compliance do portal do seu provedor de nuvem.



== O que acontece se a disposição de dados em categorias estiver ativada no Cloud Volumes ONTAP?

Você pode querer habilitar o Cloud Compliance em um sistema Cloud Volumes ONTAP que categoriza dados inativos no storage de objetos. Se a disposição de dados em categorias estiver ativada, o Cloud Compliance verifica todos os dados que estão em discos e dados inativos dispostos no storage de objetos.

A verificação de conformidade não aquece os dados frios - permanece fria e dividida em armazenamento de objetos.



== Posso usar o Cloud Compliance para analisar o storage ONTAP no local?

No momento, o Cloud Compliance está disponível como parte do Cloud Manager e é compatível com Cloud Volumes ONTAP. Estamos planejando dar suporte ao Cloud Compliance com ofertas de nuvem adicionais, como Cloud Volumes Service e Azure NetApp Files. 



== O Cloud Compliance pode enviar notificações para minha organização?

Não, mas você pode baixar relatórios de status que você pode compartilhar internamente em sua organização.



== Posso personalizar o serviço de acordo com as necessidades da minha organização?

O Cloud Compliance fornece insights prontos para uso para seus dados. Esses insights podem ser extraídos e usados para atender às necessidades da sua organização.



== Posso limitar as informações de conformidade na nuvem a usuários específicos?

Sim, o Cloud Compliance é totalmente integrado ao Cloud Manager. Os usuários do Cloud Manager só podem ver informações sobre os ambientes de trabalho que estão qualificados para visualizar de acordo com a Privileges do workspace.

link:concept_cloud_compliance.html#user-access-to-compliance-information["Saiba mais"].
