---
sidebar: sidebar 
permalink: reference_limitations.html 
keywords: limitations, active directory, ad, iscsi, key managers, ip address, govcloud, cloud manager, Cloud Volumes ONTAP 
summary: As limitações conhecidas identificam plataformas, dispositivos ou funções que não são suportadas por esta versão do produto ou que não interoperam corretamente com ele. Revise essas limitações com cuidado. 
---
= Limitações conhecidas
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
As limitações conhecidas identificam plataformas, dispositivos ou funções que não são suportadas por esta versão do produto ou que não interoperam corretamente com ele. Revise essas limitações com cuidado.



== O Cloud Manager deve permanecer em execução o tempo todo

O Cloud Manager é um componente essencial na integridade e cobrança do Cloud Volumes ONTAP. Se o Cloud Manager estiver desativado, os sistemas Cloud Volumes ONTAP serão desligados após perder a comunicação com o Cloud Manager por mais de 4 dias.



== Hosts Linux compartilhados não são suportados

O Cloud Manager não é compatível com um host compartilhado com outras aplicações. O host deve ser um host dedicado.



== O Cloud Manager não é compatível com o FlexGroup volumes

Embora o Cloud Volumes ONTAP ofereça suporte ao FlexGroup volumes, o Cloud Manager não oferece. Se você criar um volume do FlexGroup a partir do Gerenciador do sistema ou da CLI, defina o modo de gerenciamento de capacidade do Cloud Manager como Manual. O modo automático pode não funcionar corretamente com volumes FlexGroup.



== O ative Directory não é suportado por padrão com novas instalações do Cloud Manager

A partir da versão 3,4, as novas instalações do Cloud Manager não suportam o uso da autenticação do ative Directory da sua organização para gerenciamento de usuários. Se necessário, o NetApp pode ajudá-lo a configurar o ative Directory com o Cloud Manager. Clique no ícone de bate-papo no canto inferior direito do Cloud Manager para obter assistência.



== Limitações com a região AWS GovCloud (EUA)

* Se você quiser iniciar instâncias do Cloud Volumes ONTAP na região AWS GovCloud (EUA), é necessário implantar o Cloud Manager na região AWS GovCloud (EUA).
* Quando implantado na região AWS GovCloud (EUA), o Cloud Manager não consegue descobrir clusters do ONTAP em uma configuração de armazenamento privado do NetApp para Microsoft Azure ou em uma configuração de armazenamento privado do NetApp para SoftLayer.




== O Cloud Manager não configura volumes iSCSI

Ao criar um volume no Cloud Manager usando a visualização do sistema de storage, você pode escolher o protocolo NFS ou CIFS. Tem de utilizar o OnCommand System Manager para criar um volume para iSCSI.



== Limitação da Storage Virtual Machine (SVM)

O Cloud Volumes ONTAP é compatível com uma SVM de fornecimento de dados e uma ou mais SVMs usadas na recuperação de desastres. O único SVM de fornecimento de dados abrange todo o sistema Cloud Volumes ONTAP (par de HA ou nó único).

O Cloud Manager não oferece nenhuma configuração ou suporte de orquestração para a recuperação de desastres da SVM. Ele também não dá suporte a tarefas relacionadas ao storage em quaisquer SVMs adicionais. Use o System Manager ou a CLI para recuperação de desastres da SVM.
