---
sidebar: sidebar 
permalink: reference_default_configs.html 
keywords: linux, user name, operating system, installation files, installation folder, folder, log, logs, service, mysql, packages, linux,  svm, LIF, LIFs, configuration backups, attributes, autosize, security style, space guarantee, unix permissions, NTFS, UNIX, boot, root, disks, aggr0, aggr1, svm, svms, storage virtual machine, LIF failover, failover, attributes, volume attributes, boot disk, root disk, licenses, feature licenses, default licenses, ontap licenses, ontap features 
summary: Detalhes sobre como o Cloud Manager e o Cloud Volumes ONTAP são configurados por padrão podem ajudar a administrar os sistemas. 
translate: false 
---
= Configurações padrão
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Detalhes sobre como o Cloud Manager e o Cloud Volumes ONTAP são configurados por padrão podem ajudar a administrar os sistemas.



== Configuração padrão para o Cloud Manager no Linux

Se você precisar solucionar problemas do Cloud Manager ou do seu host Linux, isso pode ajudar a entender como o Cloud Manager está configurado.

* Se você implantou o Cloud Manager a partir do NetApp Cloud Central (ou diretamente do marketplace de um provedor de nuvem), observe o seguinte:
+
** Na AWS, o nome de usuário da instância do EC2 Linux é EC2-user.
** O sistema operacional da imagem do Cloud Manager é Red Hat Enterprise Linux 7,4 (HVM).
+
O sistema operacional não inclui uma GUI. Tem de utilizar um terminal para aceder ao sistema.



* A pasta de instalação do Cloud Manager reside no seguinte local:
+
/opt/application/NetApp/cloudmanager

* Os arquivos de log estão contidos na seguinte pasta:
+
/opt/application/NetApp/cloudmanager/log

* O serviço Cloud Manager é chamado occm.
* O serviço occm depende do serviço MySQL.
+
Se o serviço MySQL estiver inativo, o serviço occm também estará inativo.

* O Cloud Manager instala os seguintes pacotes no host Linux, se eles ainda não estiverem instalados:
+
** 7Zip
** AWSCLI
** Java
** Kubectl
** MySQL
** Tridentctl
** Wget






== Configuração padrão para Cloud Volumes ONTAP

Entender como o Cloud Volumes ONTAP é configurado por padrão pode ajudá-lo a configurar e administrar seus sistemas, especialmente se você estiver familiarizado com o ONTAP porque a configuração padrão do Cloud Volumes ONTAP é diferente do ONTAP.

* O Cloud Volumes ONTAP está disponível como um sistema de nó único na AWS, Azure e GCP, além de par de HA na AWS e no Azure.
* O Cloud Manager cria um SVM de fornecimento de dados quando implanta o Cloud Volumes ONTAP. O uso de vários SVMs de fornecimento de dados não é compatível.
* O Cloud Manager instala automaticamente as seguintes licenças de recurso do ONTAP no Cloud Volumes ONTAP:
+
** CIFS
** FlexCache
** FlexClone
** ISCSI
** Criptografia de volume NetApp (somente para sistemas BYOL ou PAYGO registrados)
** NFS
** SnapMirror
** SnapRestore
** SnapVault


* Várias interfaces de rede são criadas por padrão:
+
** Um LIF de gerenciamento de clusters
** Um LIF entre clusters
** LIF de gerenciamento de SVM em sistemas de HA no Azure, sistemas de nó único na AWS e, opcionalmente, em sistemas de HA em várias zonas de disponibilidade da AWS
** Um LIF de gerenciamento de nós
** Um iSCSI data LIF
** LIF de dados CIFS e NFS
+

NOTE: O failover de LIF é desativado por padrão para o Cloud Volumes ONTAP devido aos requisitos do EC2. A migração de um LIF para uma porta diferente rompe o mapeamento externo entre endereços IP e interfaces de rede na instância, tornando o LIF inacessível.



* O Cloud Volumes ONTAP envia backups de configuração para o Cloud Manager usando HTTPS.
+
Quando conetado ao Cloud Manager, os backups são acessíveis a partir do https://ipaddress/occm/offboxconfig/[]

* O Cloud Manager define alguns atributos de volume de maneira diferente de outras ferramentas de gerenciamento (System Manager ou CLI, por exemplo).
+
A tabela a seguir lista os atributos de volume que o Cloud Manager define de forma diferente dos padrões:

+
[cols="15,85"]
|===
| Atributo | Valor definido pelo Cloud Manager 


| Modo de tamanho automático | crescer 


| Dimensionamento automático máximo  a| 
1.000 por cento


NOTE: O Administrador da conta pode modificar este valor a partir da página Configurações.



| Estilo de segurança | NTFS para volumes CIFS UNIX para volumes NFS 


| Estilo de garantia de espaço | nenhum 


| Permissões UNIX (somente NFS) | 777 
|===
+
Consulte a página man _volume create_ para obter informações sobre esses atributos.





== Dados de inicialização e raiz para Cloud Volumes ONTAP

Além do storage para dados de usuário, o Cloud Manager também compra storage de nuvem para dados de inicialização e raiz em cada sistema Cloud Volumes ONTAP.



=== AWS

* Dois discos SSD de uso geral:
+
** Um disco de 140 GB para dados de raiz (um por nó)
** 9,6 e posterior: Um disco de 86 GB para dados de inicialização (um por nó)
** 9,5 e anteriores: Um disco de 45 GB para dados de inicialização (um por nó)


* Um instantâneo EBS para cada disco de arranque e disco raiz
* Para pares HA, um volume EBS para a instância Mediator, que é de aproximadamente 8 GB




=== Azure (nó único)

* Dois discos SSD premium:
+
** Um disco de 90 GB para dados de inicialização
** Um disco de 140 GB para dados de raiz


* Um snapshot do Azure para cada disco de inicialização e disco raiz




=== Azure (pares de HA)

* Dois discos SSD premium de 90 GB para o volume de inicialização (um por nó)
* Dois blobs de página de armazenamento Premium de 140 GB para o volume raiz (um por nó)
* Dois discos HDD padrão de 128 GB para guardar núcleos (um por nó)
* Um snapshot do Azure para cada disco de inicialização e disco raiz




=== GCP

* Um disco persistente padrão de 10 GB para dados de inicialização
* Um disco persistente padrão de 64 GB para dados de raiz
* Um disco persistente padrão de 500 GB para NVRAM
* Um disco persistente padrão de 216 GB para guardar núcleos
* Um snapshot do GCP para o disco de inicialização e o disco raiz




=== Onde residem os discos

O Cloud Manager estabelece o storage da seguinte forma:

* Os dados de inicialização residem em um disco conetado à instância ou à máquina virtual.
+
Este disco, que contém a imagem de arranque, não está disponível para o Cloud Volumes ONTAP.

* Os dados de raiz, que contêm a configuração e os logs do sistema, residem no aggr0.
* O volume raiz da máquina virtual de storage (SVM) reside no aggr1.
* Os volumes de dados também residem em aggr1.




=== Criptografia

Os discos de inicialização e raiz são sempre criptografados no Azure e no Google Cloud Platform porque a criptografia é habilitada por padrão nesses provedores de nuvem.

Quando você ativa a criptografia de dados na AWS usando o Serviço de Gerenciamento de chaves (KMS), os discos de inicialização e raiz do Cloud Volumes ONTAP também são criptografados. Isso inclui o disco de inicialização da instância de mediador em um par de HA. Os discos são criptografados usando o CMK selecionado quando você cria o ambiente de trabalho.
